### ISSUE TITLE
Keys of type Int

### ISSUE THREAD

**Issue by Tableau-David-Potter** [lukaskubanek/OrderedDictionary#13]
It looks like declaring the key as `Int` breaks accessing elements by index.  Try this in a playground:

``` swift
var dict = OrderedDictionary<Int, Int>
dict[0] = 1
dict[5] = 20
dict[0]
dict[5]
```

You'll get a compile error on the last two lines saying Ambiguous use of 'subscript'.

This makes complete sense, but it makes using the subscripts useless if the key type is `Int`.  Any ideas?

Thanks,
**_David_**

**Comment by lukaskubanek** [comment]
Hi David, good catch! The reason why it's not working is that the `OrderedDictionary` uses another subscript for accessing the indexed key-value pairs. ~~But it definitely makes sense to keep it consistent and use the `Int` subscript for accessing and storing the values rather than accessing the indexed key-value pairs. For the latter use case it is sufficient to have a method. I will fix it in the next release - hopefully soon. For now you can get the index for the key (`indexForKey`) and than get the element for the index (`elementAtIndex`) and finally extract the value from the element (`element.1`). I know it's cumbersome, but as I said, I will fix it in the next release.~~

**Comment by lukaskubanek** [comment]
Well, I investigated this problem a little bit further and the thing is that both subscripts indeed make sense, but you have to provide a context when using them to resolve the ambiguity. This applies only when the dictionary is using `Int` as the key and only when accessing the value for a key or when accessing the element for the index. Assignments work normally because of the type the assigned thing has.

So when you have an ordered dictionary like this:

``` swift
let dict: OrderedDictionary<Int, Int> = [0: 100, 1: 101, 2: 102]
```

You can access the value for an `Int` key by assigning the subscript call to a variable of the `Value?` type (which is `Int?` in this case):

``` swift
let value: Int? = dict[0]
```

When the variable has the type of the element (the key-value pair) which is `(Int, Int)` it looks like this:

``` swift
let element: (Int, Int) = dict[0]
```

In the upcoming release I am going to add a public method for accessing the value for key. Using that method your example would look like this:

``` swift
dict.valueForKey(0)
```
