### ISSUE TITLE
Add CocoaPods support

### ISSUE THREAD

**Issue by driver733** [lukaskubanek/OrderedDictionary#7]

**Comment by lukaskubanek** [comment]
Although CocoaPods is a widely used package manager, I don't use it myself and I don't want to support it in this library. Since there will be an official package manager for Swift I personally don't see any value in CocoaPods anymore. Before its release I suggest using Carthage or create your own podspec for this library and use it with CocoaPods.

**Comment by zmorris** [comment]
I just lost several hours to this, if someone succeeds in creating a podspec please post it here: http://stackoverflow.com/questions/35214789/cocoapods-podspec-generated-from-github-not-matching-any-source-files

UPDATE: problem appears to have been due to a caching bug in CocoaPods, the linked podspec works.
