### ISSUE TITLE
How to convert to JSON

### ISSUE THREAD

**Issue by kbala-ami** [lukaskubanek/OrderedDictionary#9]
Hi 
How to convert OrderDictionary to JSON?

Thanks

**Comment by lukaskubanek** [comment]
Hi, JSON conversion is not a feature provided by this library. You have to extend your current JSON conversion implementation by yourself. And since the JSON format does not know the concept of ordered dictionaries, do not forget to decode the ordering in a custom way, probably as a key in the decoded dictionary.

**Comment by kbala-ami** [comment]
OK Thanks for you reply. But can I convert as SwiftyJSON?

**Comment by lukaskubanek** [comment]
Sorry, but I'm not able to help you with this problem. Please consider posting your question on Stack Overflow.
